import { Story } from './types';

export const stories: Story[] = [
    {
        id: '1',
        slug: 'elephant-and-tortoise',
        title: 'Elephant and Tortoise',
        provenance: 'Told by my father, recorded 2025',
        isAuthored: false,
        transcript: [
            "Now, In those days, there used to be a village where people were residing enjoying things, everything was going on fine. But suddenly, there came an outbreak of famine. The food they were eating got exhausted. They went to farm, their farms were not yielding—everything became very hard.",
            "",
            "So, they had to call a soothsayer. A \"babaláwo\". We called them babaláwo in those days, to come and ask why those things are like this. And when the babaláwo told his oracle, he said, \"before things will become normal again in this village, there must be a sacrifice\".",
            "",
            "What are they going to use for the sacrifice? He said it's an elephant. How will they get an elephant? Elephant as you know is a very huge animal, nobody was able to confront it, and it lives in a very far place, very far away from the village.",
            "",
            "All the hunters were assembled. He asked them to look for a way of bringing an elephant to the village for the sacrifice, but none of them was able to do it.",
            "",
            "Then tortoise came out. He said, \"I can do it.\" People started laughing. \"You? Tortoise? You will bring elephant?\" Tortoise said yes.",
            "",
            "So, tortoise travelled to where the elephant was staying. On getting there, he greeted the elephant, and started talking to him sweetly. He said, \"Elephant, do you know you are the most respected in the forest? Everybody admires you.\" Elephant was happy.",
            "",
            "Tortoise then said, \"They are calling you to the village. They want to celebrate you. They want to make you king.\" Elephant said, \"Me? King?\" Tortoise said yes.",
            "",
            "So, tortoise arranged drummers, singers, and dancers. As they were coming, the elephant saw them and he was rejoicing. He followed them.",
            "",
            "On getting to the palace, they ushered the elephant into the main room where a mat was spread on top of a pit. The elephant didn't know it was a pit.",
            "",
            "They were beating drums, dancing, and singing. The moment elephant stepped on the mat, the mat sunk — gbish! — into the pit. The pit was deep. Elephant could not come out.",
            "",
            "From there, they started shooting the elephant until they killed the elephant. Finally, the elephant was used as the sacrifice.",
            "",
            "After the sacrifice, the king fulfilled his promise and gave the tortoise half of his kingdom, and they gave him everything they promised to give him. The tortoise and his wife lived happily ever after.",
            "",
            "The end."
        ],
        tags: ['Cleverness', 'Community survival', 'Sacrifice', 'Consequence'],
        daughterNote: "This one always makes me laugh… then pause.\nTortoise \"solves\" a community crisis with strategy, theatre, and deception — and it works.\nIt's the classic reminder that small doesn't mean powerless.\nBut it also raises a hard question I still sit with: what does survival justify — and who pays for it?",
        reflectionPrompt: "What did this story teach you — and do you agree?",
        contributeCTA: "If you know a similar story about survival, sacrifice, or cleverness, add it to the community sky."
    },
    {
        id: '2',
        slug: 'cock-and-fox',
        title: 'Cock and Fox',
        provenance: 'Told by my father, recorded 2025',
        isAuthored: false,
        transcript: [
            "In those days, there lived a king and the king has only one daughter. Unfortunately enough, this daughter is deaf and dumb. She cannot talk, she cannot hear, she cannot say anything.",
            "",
            "So, the king in his wisdom, he tried all his best whether he can give birth to another child but no way. All his effort proved abortive.",
            "",
            "So, he summoned everybody when the girl is about to marry. He said, \"why will I give birth to a child — a female child — a girl, and the girl cannot talk, the girl cannot hear? How? A whole human being like that?\"",
            "",
            "Then he said, \"please, if there is anybody who can make this girl talk, or hear, I will divide my kingdom into two and give a portion to the person and even allow the person to marry the girl.\"",
            "",
            "Ah! Everybody started trying their best. The elephant took the girl into the bush, he shouted into her ear but the girl could not hear anything. Lion took the girl… everybody tried.",
            "",
            "Then one day, cock said he can do it.",
            "",
            "Cock said they should bring an empty basket and a basin. He said they should take the girl and follow him to the stream.",
            "",
            "On getting to the stream, the cock started fetching water out of the stream. He caught only one fish when he dipped the basin inside the water.",
            "",
            "He carried the fish and poured it into the empty basket. You know when water and fish is poured into an empty basket, the fish will go back into the river again.",
            "",
            "So, the cock did it again. And again. And again. The girl started laughing. She laughed and laughed.",
            "",
            "The cock said, \"did you see?\" The girl laughed again and said something. That was how she started talking.",
            "",
            "So the king was happy. He gave cock a crown — a crest — and made him a person of honour.",
            "",
            "As the cock was going home with the crown on his head, fox saw the cock.",
            "",
            "Fox said, \"eh! Look at fire on the head of the cock!\" He started running.",
            "",
            "Cock, in his foolishness, said, \"ah! Fox, why are you running away from me? This thing you are seeing is not fire. Touch it! It is called crest — a crown that the king gave me.\"",
            "",
            "Fox touched it — very soft. He bit it — very sweet.",
            "",
            "He just pounced on cock and started eating cock.",
            "",
            "Since that day, if fox sees cock, he will pursue it to eat that crown on his head. That crown is the crest on his head. It is out of foolishness of the cock.",
            "",
            "Because if the cock was not foolish, he would not have told fox to come and touch it and feel it. Up till now, the fox would have still been running away from the cock, because he would think that thing he is carrying on his head is fire.",
            "",
            "The end."
        ],
        tags: ['Wisdom', 'Consequence', 'Pride', 'Don\'t overshare'],
        daughterNote: "This is one of those stories that feels like a warning wrapped in comedy.\nCock succeeds — and then ruins it by talking too much.\nIt's basically: don't explain your advantage to someone waiting to exploit it.\nAlso: not every curious question deserves an answer.",
        reflectionPrompt: "What did this story teach you — and do you agree?",
        contributeCTA: "Know a story about pride, oversharing, or someone losing what they earned? Add it."
    },
    {
        id: '3',
        slug: 'monkey-tortoise-and-lions-akara',
        title: 'Monkey, Tortoise, and the Lion\'s Akara',
        provenance: 'Told by my father, recorded 2025',
        isAuthored: false,
        transcript: [
            "Once upon a time, there was a monkey who has a very close friend called tortoise. They were always together.",
            "",
            "That period, they were moving together from one forest to another. As they were coming out of the forest, they were just strolling.",
            "",
            "Then, all of a sudden, tortoise started saying, \"Amen! Amen! Amen!\" Monkey looked at him and said, \"ahah, what is wrong with you?\" Tortoise said, \"please, God almighty, any problem, any event that we don't know the root, don't let it befall us.\" Monkey did not even answer him.",
            "",
            "Tortoise said, \"Amen!\" Monkey just left tortoise and went to his house.",
            "",
            "Tortoise was very annoyed, very angry. He said, \"ah! Because of this thing that monkey did not join me to say Amen, I will teach him a bitter lesson.\"",
            "",
            "He went home. On getting home, he told his wife Yanibo. He said, \"Yanibo, please go to the market, buy akara — sweet akara.\" His wife went, bought akara and gave to him.",
            "",
            "Tortoise said he wants to go and quickly see one of his friends. He took the akara into the bush and went to meet lion.",
            "",
            "On getting to lion's cave, he called the lion sweet names. Lion said, \"who are you?\" He said, \"please I am tortoise.\" Lion said, \"what do you want in my cave?\" Tortoise said, \"I have come to greet you and to give you food.\"",
            "",
            "Lion was surprised. Tortoise gave lion the akara. Lion ate and said it was sweet.",
            "",
            "Tortoise then said, \"do you know where I got it from?\" Lion said no. Tortoise said, \"I got it from monkey.\" Lion said, \"monkey? How?\" Tortoise said, \"it was monkey's waste product. Monkey excretes sweet akara.\"",
            "",
            "Lion said, \"eh?!\"",
            "",
            "Tortoise said, \"yes. If you hold monkey and beat him, he will excrete sweet akara.\"",
            "",
            "Lion believed him.",
            "",
            "Later, lion sent for monkey. Monkey came. Lion grabbed him and started beating him: \"excrete sweet akara!\"",
            "",
            "Monkey said, \"where will I get sweet akara to excrete?\" Lion continued beating him.",
            "",
            "Tortoise was watching and laughing.",
            "",
            "Then tortoise looked up and said, \"God almighty! The matter that we did not know the beginning or the end or the cause — please, don't let it befall us!\"",
            "",
            "Monkey shouted, \"Amen o! Amen!\" He started jumping from one tree to another saying, \"Amen! Amen! Amen!\"",
            "",
            "Since then, that's how you will see monkey jumping and shouting amen, because he didn't want any other thing to befall him again.",
            "",
            "The end! The end!"
        ],
        tags: ['Trickster', 'Revenge', 'Humiliation', '"Small" warnings matter'],
        daughterNote: "This is tortoise at peak petty.\nMonkey ignores a small ritual — so tortoise engineers embarrassment on a grand scale.\nIt's funny… but it's also a lesson about contempt: the moment you dismiss someone, you hand them motivation.\nAnd sometimes the punishment is never \"proportional\".",
        reflectionPrompt: "What did this story teach you — and do you agree?",
        contributeCTA: "If you know a story about humiliation, revenge, or tricksters, add it."
    },
    {
        id: '4',
        slug: 'bull-frog-and-race-of-pride',
        title: 'The Bull, the Frog, and the Race of Pride',
        provenance: 'Told by my father, recorded 2025',
        isAuthored: false,
        transcript: [
            "So, in this there used to be a very wicked bull — very proud, very arrogant, moving up and down saying there is nobody that can challenge him in this village.",
            "",
            "Even if elephant tries, he can run. He can run very fast.",
            "",
            "Then you know frog — frog is sluggish, big, hopping. Wherever they go to eat or drink after the day's work, bull will keep on challenging everybody.",
            "",
            "Then one day frog looked at him and said, \"you! You think you can run? You think you are strong? I will destroy you. If me and you run about 10km, I will beat you.\"",
            "",
            "Bull said, \"me? You that is hopping? You think you can?\"",
            "",
            "Frog said yes. \"Let us go to the village square!\"",
            "",
            "They organised a race between the bull and the frog.",
            "",
            "Before then, the frog has about 10 children. Frog placed his children at different points like bus stops along the race.",
            "",
            "So, the organiser put the two of them at the starting line: \"on your mark… set… go!\"",
            "",
            "The bull started running.",
            "",
            "When the bull got to the first bus stop, he saw frog there already. Bull was shocked. He said, \"how?\" He ran again.",
            "",
            "At the second stop, he saw frog again. He ran again.",
            "",
            "He didn't know it was frog's children staged at each stop.",
            "",
            "So, bull could not rest for any minute at all. He kept pushing himself harder and harder.",
            "",
            "As they got to the final end, he saw frog again. Bull said he has been defeated.",
            "",
            "Bull then went to the stream and started drinking water greedily: gboo gboo gboo.",
            "",
            "And you know, bull, when they are too thirsty, they are not allowed to drink water hastily like that.",
            "",
            "As he was drinking, what is called \"aoroko\" gripped him. His stomach swelled, and he died suddenly.",
            "",
            "That is how the bull ended his life by himself because of pride.",
            "",
            "The end."
        ],
        tags: ['Pride', 'Strategy', 'Teamwork', 'Don\'t underestimate'],
        daughterNote: "I love how this one teaches \"strategy beats noise.\"\nBull has ego. Frog has a plan — and support.\nAnd the real punishment isn't even the race… it's what bull does after losing.\nA story about pride, panic, and self-destruction.",
        reflectionPrompt: "What did this story teach you — and do you agree?",
        contributeCTA: "If you know a story about pride, strategy, or underestimating someone, add it."
    },
    {
        id: '5',
        slug: 'tortoise-and-golden-spoon',
        title: 'Tortoise and the Golden Spoon',
        provenance: 'Told by my father, recorded 2025',
        isAuthored: false,
        transcript: [
            "This is another story that centred on the tortoise, the king and their community. The story goes on like this:",
            "",
            "In those days, there was a famine in the community where tortoise lived. No food, everything was dry, farm products were not yielding what it's supposed to yield. So the farming was too much. Everybody was loving up and down looking for what to eat. So, this faithful day, tortoise went to the farm. On getting there, nothing to…ah! Eeeeh! As tortoise was going, he now saw a palm tree. He looked at the top of the palm tree and saw a ripe very ripe palm fruit. Ah! Tortoise was very happy! He then climbed the palm tree. On getting to the top, he plucked the palm fruit. As he was plucking it, palm fruit slipped from his hand and fell. Ah! Down at the bottom of the palm tree, a little mermaid was standing looking at the top and watching what tortoise was doing. Before tortoise could come down, the little mermaid took the palm fruit and ran into the river. Eh! What did tortoise see?? Tortoise started shouting, \"eeeh! Eeeh! Eehhh! Please drop it! Drop it!\"",
            "",
            "The little mermaid has entered into the river. Ha! Kai! The tortoise could not stand it. He followed the little mermaid and started singing:",
            "",
            "Ogun gba bo, tere",
            "Ogun gba bo, tere",
            "Ma wi alara, tere",
            "Ma wi olona, tere",
            "Ma wi ojale, tere",
            "Ma wi o ko su wewewe, ona eje ro, tere",
            "Ogun gba bo, tere",
            "Ogun gba bo, tere",
            "Ogun gba bo, tere",
            "Ma wi alara, tere",
            "Ma wi olona, tere",
            "Ma wi ojale, tere",
            "Ma wi o ko su wewewe, ona eje ro, tere",
            "",
            "This song means that ye! You little mermaid! You have stolen my property! I will tell this, I will tell that! I will tell them that you have stolen! You have packed all the yam by side of the road! Stop it!",
            "",
            "The little mermaid did not answer, it went straight down into the river and stayed with its mother mermaid. On getting there, the tortoise met the two of them. By then, the little mermaid had started eating the palm fruit.",
            "",
            "'Heey! Give me my palm fruit! Give me my palm fruit!' The mother mermaid 'relax what is the problem?' Tortoise narrated the story, how there was famine in their land and how he has been looking for food and saw this. Then the mother mermaid said, don't worry I will give you something in exchange for this. So she now went into the room and came out with a spoon, a golden spoon that looked like calabash. She gave it to tortoise. 'When you get to your house, ask this golden spoon what it can do for you. Then the golden spoon will perform a miracle.' Toh! The tortoise has no choice. He agreed and went home. On getting home, he locked himself into the room and asked, \"you golden spoon, what can you do?\" The spoon said, \"ah! I am the one that can prepare food. Any type of food you want, I can prepare! I can prepare! I can prepare until you eat and get satisfied!\" \"Ah!\" Tortoise said, \"prepare it and let's see!\" Immediately, the whole room was filled with assorted food! Ah! Tortoise started eating! He ate and ate and ate until he could eat no more. After, the piled the rest of the food and put them aside. Quickly, tortoise went to the kings palace and said, \"king! O king! May you live long! I have caught blessing. I am going to satisfy the whole of this community with what I have and I will show them that yes! I am the one! The only one that can do it in this community!\" \"Aah aah!\" The king said, \"what do you mean? Do it now and let's see now!\" Tortoise now asked the king to gather everybody. They gathered them into the hall and he asked the golden spoon what he can do. The golden spoon still repeat the same thing. He dishes out food for everybody, they ate and ate and ate and were satisfied! In the process of dancing and struggling, a very big rodent, rat, fell on top of the golden spoon and the golden spoon got broken! Thereafter, the golden spoon could not perform the miracle again.",
            "",
            "Kai! Tortoise said, what is the meaning of this?! I will have to go back to mother mermaid to collect another one! He went, but unfortunately enough for him, there was no ripe palm fruit on top of the palm tree. He climbed and plucked one unripe one. He threw it down but the little mermaid was not there to pick it up. He now, by himself, threw the palm fruit into the river. The palm fruit turned and tortoise followed it. On getting to the bottom of the river, he met the mermaid and said, \"please, mother, I have come. Give me another spoon.\" The mother mermaid said, \"ah ah! There is no spoon here again. Okay let me give you what I have\" She now looked under her bed and gave tortoise a stick, that looked like a whip. She said when you get to the house, ask this material what it can do.",
            "",
            "On getting to the house, the tortoise first of all locked himself into the room and asked the material what it can do. The material said, \"I am a whip, a very fine whip, and I can flog and flog and flog and flog\" tortoise said, \"aah aah! Flog?! Demonstrate it and let's see!\" The whip hot up and started flogging tortoise. He flogged tortoise mercilessly. Tortoise shouted and shouted and shouted! Nobody! Because he locked himself into his room, nobody know what was happening.",
            "",
            "At the end of the period, the whip now stopped. Chai! Tortoise said me?! I'm not going to be the only one that will suffer this! I have to go to the kings palace! Because they ate with me, they must enjoy this thing with me!",
            "",
            "Then, the tortoise left. On getting to the kings palace, he call the king, and said, \"o king! I have come with another miracle! Please, summon your people and let’s enjoy it.\" This time around, the king called a lot of dignitaries from other communities to come and enjoy what he has been enjoying. Because the story of what happened last time has gone across so many communities in their neighbourhood. So, they all gathered in the town hall. They locked themself and they asked tortoise to start the operation. Before then, tortoise has ordered them to bring a very new, a very big mortar, very close to himself wanting to do something with the mortar. After asking the stick what it can do, and the stick told them what it could do, tortoise quickly ran under the mortar, and use to mortar to cover himself. The whip started flogging! It flogged the king! It flogged the dignitaries! It flogged everybody! They were shouting, they were wailing, they were crying! In the process of struggling, somebody now stumbled under that mortar and the mortar now flung open! Haa! On sighing tortoise, the whip started flogging! It flogged all of them! They were tired, crying, and shouting. Then it stopped.",
            "",
            "On seeing this, the king was very sad. The king was very angry. He said, \"ha! Tortoise! For what you have done, I'm going to deal with you! Because you have brought a lot of disgrace upon me. In the presence of my dignitaries and everybody, you allowed a whip to flog me? Me, king?! Now, pack your load, your family and everything and get out of my community!\" That was how the king banished the tortoise and the family from that community.",
            "",
            "The end."
        ],
        tags: ['Greed', 'Magical consequences', 'Exploitation', 'Public disgrace'],
        daughterNote: "This story is basically \"free gifts come with rules.\"\nTortoise receives help in a crisis, then turns it into a performance — and it backfires loudly.\nIt's the part about public disgrace that stays with me: sometimes your punishment isn't private.\nSometimes it's social.",
        reflectionPrompt: "What did this story teach you — and do you agree?",
        contributeCTA: "If you know a story about greed, gifts, magic, or disgrace, add it."
    },
    {
        id: '6',
        slug: 'farmer-and-bird-of-gold',
        title: 'The Farmer and the Bird of Gold',
        provenance: 'Told by my father, recorded 2025',
        isAuthored: false,
        transcript: [
            "Hello my little girl, this is another story. A story between a young poor farmer and a bird. The story teaches us to be very very careful and always very very thoughtful in anything we do.",
            "",
            "Once upon a time, there was a poor young farmer who could hardly afford to feed his family. As he was going to his farm early in the morning, he caught a bird. He was happy that he was going to use the bird to prepare a delicious meal with his family.",
            "",
            "But when the bird was in his hand, the bird said to him, \"please don't kill me. I will tell you 3 good things that will make you very rich.\"",
            "",
            "The man said, \"eh-ehn?! Are you sure? Okay! Go on, tell me.\"",
            "",
            "The bird said, \"please listen to me carefully.\"",
            "",
            "The man said, \"yes, I'm with you.\"",
            "",
            "The bird said:",
            "",
            "\"When somebody tells you something, please listen carefully and think about it before you act.\"",
            "",
            "\"In this world, do not ever cry for what you can't have.\"",
            "",
            "(Then the bird continued speaking about riches and things that can tempt a person.)",
            "",
            "The man agreed, but he did not truly understand.",
            "",
            "The bird then asked to fly to a tree branch so it could speak \"comfortably.\" The man agreed. Once the bird flew, the man began to panic and regret.",
            "",
            "The bird reminded him: \"Didn't I tell you to think before you act? Did you do that? No.\"",
            "",
            "The bird also reminded him: \"Didn't I tell you not to cry for what you can't have? Now you are crying for what you can never have again.\"",
            "",
            "The bird said, \"O foolish man! You have lost everything!\" Then it flew away.",
            "",
            "The end."
        ],
        tags: ['Think before you act', 'Regret', 'Self-control', 'Listening'],
        daughterNote: "This one is direct moral teaching — no hiding.\nThe bird basically hands him wisdom… and he still fumbles it.\nIt's the most \"adult\" story here: about impulsiveness, regret, and wanting what you can't keep.\nSometimes the moral isn't poetic. It's plain.",
        reflectionPrompt: "What did this story teach you — and do you agree?",
        contributeCTA: "If you know a story about regret, patience, or \"think before you act\", add it."
    },
    {
        id: '7',
        slug: 'girl-who-greeted-moon-twice',
        title: 'The Girl Who Greeted the Moon Twice',
        provenance: 'Written by me, Deborah Adeoye, Plymouth, 2025',
        isAuthored: true,
        transcript: [
            "At dusk, when the road thinned to thread and the houses put on their evening voices, Iyeoma stood at the edge of the forest and watched the moon try on shapes. First a calabash lip, then a fisherman’s hook, then the soft belly of a yam turned to the sky. She had the kind of feet that could pass a sleeping chicken without waking its dream, and the kind of heart that wanted a different sky—not to own it, only to hear what it would say if it noticed her.",
            "",
            "People in her town had begun to speak in gaps. A proverb would come out with a hole where the spice should be. A lullaby would pause, and the child would frown because the next line went missing on the mother's tongue. \"Where did that story go?\" children asked. The elders tapped their foreheads and said, \"Ah,\" and then forgot what they had meant to say about forgetting.",
            "",
            "They blamed a creature the hunters had not caught and the priests had not named. Some called it the Wanderer, some the Cradle, and the children, who love knitting, tied the names together behind its back and called it Egberepolu. That night Iyeoma followed a thread of backward footprints into the trees, the kind of prints that promise to take you home and then leave you a little wiser about your own feet. The air smelled of raffia and night water. Somewhere a mortar was speaking softly to a pestle about yam.",
            "",
            "\"Don't be long,\" her mother had said, pinning a small lamp to her wrapper. \"And don't feed anything that doesn't have a mother.\"",
            "",
            "\"I hear,\" Iyeoma said, and meant it.",
            "",
            "She did not go to be brave or to be first. She went because the holes in the town's speaking had started to feel like holes in her own body, tiny drafts that made her reach for a wrapper even when the weather was kind.",
            "",
            "Egberepolu found her before she found it, as is the way with those who were born to be found. The creature stepped sideways out of the shadow of a silk-cotton tree and smiled with cowry teeth. Its feet were backward—heels where toes should be—so that the path behind its body looked tidy and the path before it looked troubled. It carried a shallow cradle on a strap across its chest, a repository for what it had eaten and could not digest. Its belly was round as a market drum and hummed, not with hunger, but with the muffled chorus of stolen tales.",
            "",
            "It did not smell of blood. It smelled of palm oil and old paper. When it breathed, a few ember motes lifted from its nostrils, and went out, then returned, the way curious fireflies do.",
            "",
            "\"You have come to ask me about holes,\" Egberepolu said, each word a little foggy around the edges, like the memory of a song. Its voice was not cruel. It was tired with the fullness that comes from eating the wrong things. \"I have come,\" Iyeoma answered, \"to ask for what belongs to us.\"",
            "",
            "The creature laughed like a goatskin being stretched over a frame. \"Belongs,\" it said. \"Such a heavy word for a light thing. Does the wind belong? Does a proverb? My mother dropped me in a cradle and said, 'Carry what you can.' I found that I could carry what people forgot without breaking my back. I became a house for dropped things.\"",
            "",
            "\"You became a hole,\" Iyeoma said, and then smiled to show she meant an observation not an insult.",
            "",
            "\"A hole is also a home,\" Egberepolu said. \"Come, girl-who-walks-soft. If you can make me cry, I will open my cradle and return what I have eaten. But I do not cry for scraped knees or for prayers without salt. I cry for what remembers itself.\" It leaned forward, and its mouth opened—not like a trap, but like a threshold. \"Enter and speak.\"",
            "",
            "Iyeoma did not look back. Sometimes the only way to respect a fear is to walk into it before it finishes naming itself. She set her lamp on a root and climbed forward, the way one climbs into a canoe that has promised not to throw you.",
            "",
            "Inside was not a stomach like in books. Inside was a room.",
            "",
            "The walls were woven like mats, the weave loose enough to breathe. A palm-oil sheen caught the lamplight and made a small road out of smoke. The floor sighed as if someone had just stood up to make space for her. Ember motes drifted and died and came again. The air held a smell like the moment a pot is lifted and steam remembers it can be a river.",
            "",
            "Iyeoma laid her hand on the wall and spoke a line her grandmother used to say when she picked up a book with the gentleness she reserved for babies and the first day of yam harvest—words that remember their work.",
            "",
            "\"Ìtàn tí a bá bójú tó, tún ń bójú t’ẹni.\"",
            "",
            "(The story you tend will, in turn, tend you.)",
            "",
            "The wall warmed under her palm. Egberepolu, outside, settled on its haunches and placed both backward feet neatly together. Its cowry teeth stopped smiling and began, very slowly, to listen.",
            "",
            "Iyeoma cleared her throat and took from her pocket three small stones. She liked to hold things when she told things. She put the stones in a row and began.",
            "",
            "The Boy Who Swallowed Fire",
            "",
            "They said the blacksmith's son had a small voice, so one evening he borrowed a coal. He pressed it to his lips the way a brave person kisses trouble, and swallowed before the fear could run. After that his breath carried a curl of smoke, and his tongue shone the color of palm oil. When he spoke, vowels crackled; when he laughed, a red thread stitched the air. People noticed him then—oh they noticed—but the praise burned on the way out. \"Well done,\" they said, and the \"well\" blistered. \"Sing,\" they said, and the \"s\" hissed like a snake under a pot. He tried to cough the ember back, but the ember had learned his ribs. His mother did not pour water on him. She placed a calabash beside his bed and told him stories at a whisper until the coal climbed out to listen, and cooled itself in the bowl.",
            "",
            "The room sighed like a person who had been holding one breath for too long and had decided to take two. The motes brightened, then dimmed. Iyeoma rolled the second stone to the center of her palm.",
            "",
            "The Girl Who Turned to Dust",
            "",
            "In a busy town lived a girl whose name nobody bothered to say. \"You,\" they called, or \"Move,\" or \"Later,\" as if later were a person with hands. Each time someone refused her a name, a fingertip powdered; each slight drew a chalk line from wrist to elbow, from elbow to shoulder, until sweeping became her shadow. Wind learned her first. It lifted what she had become and filed it into the shutters of people who passed her, into the spines of books that forgot children, into the cracks of the church steps where no one knelt long enough to notice. One evening an old woman washed her doorway and hummed a tune that remembered how names are carried. She spoke the girl's name softly—twice—and the dust in the woman's bucket settled into letters, then into hands, then into a face. The girl stood there, wet with her own return, and the broom leaned like a witness.",
            "",
            "The wall pressed back against Iyeoma's palm as if to say, Continue. Somewhere far off, a pestle lifted and fell, lifted and fell, and the sound it made was not work but keeping. Iyeoma took the third stone.",
            "",
            "The Drum That Played When Nobody Watched",
            "",
            "It was a fat talking drum with a shy heart. In the market it sat proud on the mat, goats nosing the leather, sellers clapping, children craning their necks. \"Play!\" they cried, and the drum did what shy things do—it forgot its mouth. Eyes, too many eyes, stitched it shut. But at night a widow would sweep her small yard and turn her back to the stool where the drum waited. She spoke to the broom about the man who used to dance crooked, how one heel always came late to the ground. The drum listened, then sighed. When the yard faced away—the widow, the broom, the moon—it remembered its road. A small rhythm stood up, then another, and the steps came, the exact, faithful crook of them, walking her grief to the gate. In the morning the children asked, \"Did it play?\" and the drum sat quiet like a secret keeping someone warm.",
            "",
            "Silence came in with both feet. Iyeoma put the three stones back in her pocket and touched the wall again.",
            "",
            "\"Ìtàn tí a bá bójú tó, tún ń bójú t’ẹni.\"",
            "",
            "(The story you tend will, in turn, tend you.)",
            "",
            "Outside, Egberepolu made a sound like a cradle rope moving against a beam. It was not a cry yet. It was the sound that happens before a cry, when the body takes attendance of all its waters. Then a drop fell—ink-black, heavy as a word you waited too long to speak. It struck the ground and broke into a little spark. Another fell, and another, and soon the clearing shivered with small lights like ideas learning to walk.",
            "",
            "\"I remember,\" Egberepolu said, voice thin with relief. \"I was made to cradle, not consume.\" It put its backward feet together as if praying with the soles. Its edges loosened, unstitched, unraveled into smoke. No blood, no meat—only the kind of ash that knows it is useful for gardens. The sparks drifted upward, then downward, then sideways, as if deciding, the way stories do, where they were most needed.",
            "",
            "Not all bargains end with a gift. Some end with a price that is also a door.",
            "",
            "The voice that came next was not Egberepolu’s and not any elder's. It was the voice the world uses when it remembers its rules. It spoke from the cradle that now lay empty on the ground.",
            "",
            "\"For one lunar cycle,\" the voice said, \"your mouth shall not hold your own name. When another speaks it with kindness, a spark shall descend and return one lost piece of story near that person. Unkind calling will do nothing. You will learn how a name tastes in other mouths. This is how cradles are mended.\"",
            "",
            "Iyeoma's first thought was laughter—small, surprised. Her second was worry—how to answer if someone asked her who she was. Her third was relief—no knives, no blood, a price in the currency of listening. She put a hand to her throat and made a silly face until both laughed with her, not at her, and then the first child said her name in full, careful and affectionate, as if balancing a bird. A spark fell into the second child's hair, and later that night his mother remembered the last verse of a song she had been skipping for years.",
            "",
            "At the bakery she discovered the first puzzle of a person without a name. The baker, covered in honest flour, asked, \"Who ordered the small loaf?\" She opened her mouth and closed it again and mimed a loaf the size of her hand. He laughed. \"You,\" he said, as if you were a name with vowels and a father. \"You again.\" A woman at the end of the line, who had seen Iyeoma help her carry water last week, said, \"It's for Iyeoma,\" softly, not to show off but to show care. The spark that dropped into the bread basket smelled faintly of cardamom and good timing. When the baker sliced the loaf at home, he remembered a riddle his mother used to teach counting, and taught it to his own boy before the boy slept.",
            "",
            "Iyeoma found that a person without a name in her own mouth becomes light in useful places. You can slip under doors that would otherwise look at you and ask for a password. You can listen with more surface area. You can choose to overhear things that need your carrying. She learned to answer questions with stories that were also answers. \"Who is responsible for this mischief?\" asked the woman with the sharp laugh, and Iyeoma shrugged and said, \"Have you ever noticed how a drum behaves when everyone is staring?\" The woman forgot to laugh first that day, and a small spark nested in her kerchief and stayed there until she gave it away, which was the point of it.",
            "",
            "Children are the best engineers of kindness because they have not yet been paid to forget how. They began to experiment. \"If I say it while braiding her hair, will the spark help my mother remember the recipe for bean cakes?\" Yes. \"If I whisper it into the well, will it help the old story about the yam festival find the right tune?\" Perhaps. \"If I shout it into the well?\" No. Wells are good listeners but they do not decide what the world does with what they hear.",
            "",
            "Days collected themselves into a calendar. The town fattened—not its stomachs, which still had their seasons, but its speaking. Lullabies closed their loops. Proverbs remembered their spices. Children told jokes whose endings arrived on time. A widow found, at the bottom of her trunk, a letter from her husband she had never noticed, and when she read it, his crooked dance stepped once more in her yard. The drum across the road behaved itself, and misbehaved when needed, and both behaviours were right.",
            "",
            "There was one thing that did not come back. When Iyeoma was very small and learned to stand, her grandfather had taken to calling her Moonfly, because she walked toward the brightest circle in any room and because her feet seemed to know how to lift before her mind had decided. Moonfly was not her government name, not the one a clerk would write in a book, but it was the name that made her feel threaded to people who would rescue a dropped bead before a broom got it. No one said Moonfly that month. Perhaps they remembered it with a smile and a shake of the head and thought, \"Later.\" Perhaps they filed it in the wrong drawer of their mouths.",
            "",
            "On the last night of the cycle, the moon climbed the same silk-cotton tree Egberepolu had once borrowed for an entrance. The town had settled itself—goats arguing politely, babies making successful bargains with sleep. Iyeoma stood at the edge of the square and felt her mouth like a room she had cleaned for visitors. The elders were playing ayo under the almond tree. One of them, the one who had pinched her cheeks when she was new, looked up and frowned the way people frown when they are about to remember a spice. He put down a seed. He cleared his throat.",
            "",
            "\"Moonfly,\" he said, not loudly, not for show, but because the word had tapped his own teeth from behind and asked to be let out kindly.",
            "",
            "The last spark came down without hurry and sat on the edge of the ayo board like a third player who had learned to be patient. Somewhere a lullaby finished its route and bowed. Somewhere a proverb took off its wrapper and went to work. Somewhere the broom in the widow's yard leaned like a friend waiting at a gate.",
            "",
            "Iyeoma touched her throat and laughed a laugh that did not blister anyone. She still did not say her name. Not yet. Sometimes keeping a promise is a way to keep from breaking something fragile just because the time has run out. She walked to the church steps and sat where the cracks held the dust of old feet. She thought of Egberepolu becoming smoke and of the cradle lying empty, and she felt the particular tiredness that is a kind of joy, the weight you carry when you are the right person for a task that almost nobody sees.",
            "",
            "She stood. She lifted the small lamp her mother had pinned to her wrapper. She looked up at the moon, which had decided on a shape that made room for both hunger and rest.",
            "",
            "She greeted it once, in the language the town understood, and once in the quiet language the forest had taught her.",
            "",
            "She greeted the moon twice—once for the sky's mirror, once for the heart's—and both greetings knew her name."
        ],
        tags: ['Stewardship', 'Memory', 'Sharing', 'Loss', 'Lineage'],
        daughterNote: "This is my reply back to the archive.\nIt's not a \"traditional\" animal tale — it's a moon story about language leaking away when people stop carrying it with care.\nI wrote it as a continuation: what happens when stories don't just entertain, but hold a community together?",
        reflectionPrompt: "What did this story teach you — and do you agree?",
        contributeCTA: "If you have a proverb, story, or line you were taught growing up — add it to the community sky."
    }
];
